export const colors = [
  { name: "Red", hex: "#f87171" },
  { name: "Orange", hex: "#fb923c" },
  { name: "Amber", hex: "#fbbf24" },
  { name: "Yellow", hex: "#facc15" },
  { name: "Lime", hex: "#a3e635" },
  { name: "Green", hex: "#4ade80" },
  { name: "Emerald", hex: "#34d399" },
  { name: "Teal", hex: "#2dd4bf" },
  { name: "Cyan", hex: "#22d3ee" },
  { name: "Sky", hex: "#38bdf8" },
  { name: "Blue", hex: "#60a5fa" },
  { name: "Indigo", hex: "#818cf8" },
  { name: "Violet", hex: "#a78bfa" },
  { name: "Purple", hex: "#c084fc" },
  { name: "Fuchsia", hex: "#e879f9" },
  { name: "Pink", hex: "#f472b6" },
] as const;
